import getPost from '@/lib/getPost';
import React from 'react'

export async function generateMetadata() {
  return ({
    title: "Sub page 1",
    description: "Generated by next app"
  })
}

const page = async(id) => {
  // console.log(id)
  const post = await getPost(id);

  return (
    <div>
      <h2>{post.title}</h2>
      <p>{post.body}</p>
    </div>
  )
}

export default page
